Traceback (most recent call last):
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\salin\anaconda3\envs\book\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\salin\anaconda3\envs\book\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Cost function
h = lambda z: 1/(1+np.exp(-z))
J1 = lambda z,y: -y*np.log(h(z))
J2 = lambda z,y: -(1-y)*np.log(1-h(z))

# Ref metricas
m1 = lambda z: z-1 



#===================
z1 = np.linspace(-2, 10)
z2 = np.linspace(-10, 2)
plt.plot(z1,J1(z1,1), label="y=1")

plt.plot(z2,J2(z2,0), label="y=0")
plt.legend()
plt.xlabel("Z")
plt.ylabel("Cost function")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 12>[1;34m()[0m
[0;32m      7[0m m1 [38;5;241m=[39m [38;5;28;01mlambda[39;00m z: z[38;5;241m-[39m[38;5;241m1[39m 
[0;32m     11[0m [38;5;66;03m#===================[39;00m
[1;32m---> 12[0m z1 [38;5;241m=[39m [43mnp[49m[38;5;241m.[39mlinspace([38;5;241m-[39m[38;5;241m2[39m, [38;5;241m10[39m)
[0;32m     13[0m z2 [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m-[39m[38;5;241m10[39m, [38;5;241m2[39m)
[0;32m     14[0m plt[38;5;241m.[39mplot(z1,J1(z1,[38;5;241m1[39m), label[38;5;241m=[39m[38;5;124m"[39m[38;5;124my=1[39m[38;5;124m"[39m)

[1;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

